myapp/urls.py
#from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

app_name = 'myapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('robots\.txt', lambda r: HttpResponse('User-agent: *\nDisallow: /', content_type='text/plain')),
    path('admin/', admin.site.urls),
    path(
        'home',
        TemplateView.as_view(template_name='home.html'),
        name='home'
    ),
    path(
        'files/',
        include('db_file_storage.urls')
    ),
    path(
        'model_files/',
        include('model_filefields_example.urls', namespace='model_files')
    ),
    path(
        'form_wizard/',
include('form_wizard_example.urls', namespace='form_wizard'))
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#if settings.DEBUG:
#  urlpatterns += [
#      re_path(r'^media/(?P<path>.*)$', serve, {
#        'document_root': settings.MEDIA_ROOT, }),
#      ]

old_myapp/polls/urls.py
from django.views.generic import TemplateView
from django.urls import path, include
from django.contrib import admin

from . import views

app_name = 'polls'
urlpatterns = [
#    path('', TemplateView.as_view(template_name="index.html")),
    path('admin/', admin.site.urls),
    #path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

old_myapp/urls.py
#from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html")),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
  urlpatterns += [
      re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT }),
      re_path(r'^static/(?P<path>.*)$', serve, {
        'document_root': settings.STATIC_ROOT + 'static/',
        }),
      ]

polls/urls.py
from django.views.generic import TemplateView
from django.urls import path, include

from . import views

app_name = 'polls'
urlpatterns = [
#    path('', TemplateView.as_view(template_name="index.html")),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

old_myapp/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
  question_text = models.CharField(max_length=200)
  pub_date = models.DateTimeField('date published')
  
  def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date >= timezone.now() <= now

  was_published_recently.admin_order_field = 'pub_date'
  was_published_recently.boolean = True
  was_published_recently.short_description = 'Published recently?' 
  
  def __str__(self):
    return self.question_text



class Choice(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=200)
  votes = models.IntegerField(default=0)
  
  def __str__(self):
    return self.choice_text
  
  def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now

old_myapp/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
  template_name = 'polls/index.html'
  context_object_name = 'latest_question_list'

  def get_queryset(self):
    """Return the last five published questions."""
    return Question.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
  model = Question
  template_name = 'polls/detail.html'

#  def get_queryset(self):
   # return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
#    return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/base.html
<DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en">
<head>
<meta charset="utf-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Foundation 5</title>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/css/normalize.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/css/foundation.min.css">
<link href='https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css' rel='stylesheet' type='text/css'>

<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
</head>
<body>
<div class="row">
<div class="large-12 columns">
<ul class="button-group">
<li><a href="#" class="button">Link 1</a></li>
<li><a href="#" class="button">Link 2</a></li>
<li><a href="#" class="button">Link 3</a></li>
<li><a href="#" class="button">Link 4</a></li>
<li><a href="#" class="button">Link 5</a></li>
<li><a href="#" class="button">Link 6</a></li>
</ul>

<p><img src="https://placehold.it/1000x400&text=[banner img]" /></p>
</div>
</div>

<div class="hero-full-screen">

  <div class="top-content-section">
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="menu">
          <li class="menu-text"><img src="http://placehold.it/75x30" alt="logo"></li>
          <li><a href="#">One</a></li>
          <li><a href="#">Two</a></li>
          <li><a href="#">Three</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="middle-content-section">
    <h1>Super Compelling Headline</h1>
    <button class="button large">Button</button>
    <button class="button large">Button</button>
  </div>

  <div class="bottom-content-section" data-magellan data-threshold="0">
    <a href="#main-content-section"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M24 12c0-6.627-5.373-12-12-12s-12 5.373-12 12 5.373 12 12 12 12-5.373 12-12zm-18.005-1.568l1.415-1.414 4.59 4.574 4.579-4.574 1.416 1.414-5.995 5.988-6.005-5.988z"/></svg></a>
  </div>

</div>

<div id="main-content-section" data-magellan-target="main-content-section">
  <!-- your content goes here -->
</div>



<div class="row">
<div class="large-8 columns">
<h4>This is a content section.</h4>
<p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
<p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
<p><a href="#" class="secondary small button">Next Page &rarr;</a></p>
</div>
<div class="large-4 columns">

<ul class="small-block-grid-3">
<li><a href="#"><img src="https://placehold.it/120x120" /></a></li>
<li><a href="#"><img src="https://placehold.it/120x120" /></a></li>
<li><a href="#"><img src="https://placehold.it/120x120" /></a></li>
<li><a href="#"><img src="https://placehold.it/120x120" /></a></li>
<li><a href="#"><img src="https://placehold.it/120x120" /></a></li>
<li><a href="#"><img src="https://placehold.it/120x120" /></a></li>
</ul>
</div>
</div>

<div class="row">
<div class="large-12 columns">
<div class="panel">
<h4>Get in touch!</h4>
<div class="row">
<div class="large-9 columns">
<p>We'd love to hear from you, you attractive person you.</p>
</div>
<div class="large-3 columns">
<a href="#" class="radius button right">Contact Us</a>
</div>
</div>
</div>
</div>
</div>

<footer class="row">
<div class="large-12 columns">
<hr />
<div class="row">
<div class="large-6 columns">
<p>&copy; Copyright no one at all. Go to town.</p>
</div>
<div class="large-6 columns">
<ul class="inline-list right">
<li><a href="#">Link 1</a></li>
<li><a href="#">Link 2</a></li>
<li><a href="#">Link 3</a></li>
<li><a href="#">Link 4</a></li>
<li><a href="#">Link 5</a></li>
<li><a href="#">Link 6</a></li>
</ul>
</div>
</div>
</div>
</footer>
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/js/foundation.min.js"></script>
<script>
    $(document).foundation();
  </script>
</body>
</html>

polls/templates/base0.html
<DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en">
<head>
<meta charset="utf-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Foundation 5</title>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/css/normalize.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/css/foundation.min.css">
<link href='https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css' rel='stylesheet' type='text/css'>

<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
</head>
<body>
<div class="row">
<div class="large-12 columns">
<ul class="button-group">
<li><a href="#" class="button">Link 1</a></li>
<li><a href="#" class="button">Link 2</a></li>
<li><a href="#" class="button">Link 3</a></li>
<li><a href="#" class="button">Link 4</a></li>
<li><a href="#" class="button">Link 5</a></li>
<li><a href="#" class="button">Link 6</a></li>
</ul>

<p><img src="https://placehold.it/1000x400&text=[banner img]" /></p>
</div>
</div>


<div class="row">
<div class="large-8 columns">
<h4>This is a content section.</h4>
<p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
<p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
<p><a href="#" class="secondary small button">Next Page &rarr;</a></p>
</div>
<div class="large-4 columns">

<ul class="small-block-grid-3">
<li><a href="#"><img src="https://placehold.it/120x120" /></a></li>
<li><a href="#"><img src="https://placehold.it/120x120" /></a></li>
<li><a href="#"><img src="https://placehold.it/120x120" /></a></li>
<li><a href="#"><img src="https://placehold.it/120x120" /></a></li>
<li><a href="#"><img src="https://placehold.it/120x120" /></a></li>
<li><a href="#"><img src="https://placehold.it/120x120" /></a></li>
</ul>
</div>
</div>

<div class="row">
<div class="large-12 columns">
<div class="panel">
<h4>Get in touch!</h4>
<div class="row">
<div class="large-9 columns">
<p>We'd love to hear from you, you attractive person you.</p>
</div>
<div class="large-3 columns">
<a href="#" class="radius button right">Contact Us</a>
</div>
</div>
</div>
</div>
</div>

<footer class="row">
<div class="large-12 columns">
<hr />
<div class="row">
<div class="large-6 columns">
<p>&copy; Copyright no one at all. Go to town.</p>
</div>
<div class="large-6 columns">
<ul class="inline-list right">
<li><a href="#">Link 1</a></li>
<li><a href="#">Link 2</a></li>
<li><a href="#">Link 3</a></li>
<li><a href="#">Link 4</a></li>
<li><a href="#">Link 5</a></li>
<li><a href="#">Link 6</a></li>
</ul>
</div>
</div>
</div>
</footer>
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/js/foundation.min.js"></script>
<script>
    $(document).foundation();
  </script>
</body>
</html>

polls/templates/home.html
{% load static %}

<!-- <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> -->
<p>Hello World!</p>

polls/templates/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<p>This color is blue.</p>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}